# Generated by Django 5.0.3 on 2024-03-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingmodel',
            name='file_type',
            field=models.CharField(blank=True, default='image', max_length=50, null=True),
        ),
    ]
