# Generated by Django 5.0.3 on 2024-03-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_codingmodel_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingmodel',
            name='algorithm',
            field=models.CharField(max_length=10),
        ),
    ]
