# Generated by Django 5.0.3 on 2024-03-10 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_codingmodel_spreading_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('coding_type', models.CharField(max_length=10)),
                ('coding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.codingmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
