# Generated by Django 5.0.3 on 2024-03-10 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_statsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='statsmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 3, 10, 11, 22, 32, 724923, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statsmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
