# Generated by Django 5.0.3 on 2024-03-12 14:17

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_statsmodel_created_at_statsmodel_updated_at'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
