# Generated by Django 5.0.3 on 2024-03-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_usermodel_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_third_party',
            field=models.BooleanField(default=False),
        ),
    ]
